

  default_twitter: &default_twitter
  twitter_api_key: 'UFvaMN5T2CAtxjwVt3AgvdClz'
  twitter_api_secret: 'B4LW9Dvdc8NJ3LBLH3NwpUTaPRZoVSs3HfReBkZQOCLpLs8bNX'

development:
  secret_key_base: 1466aac22e6a869134be3d09b9e89232fc2c2289
  <<: *default_twitter

test:
  secret_key_base: 842ad9481c7b0e844bd53f3650de4b5a
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
